export default {
  plugins: {
    "@tailwindcss/postcss": {},
  },
  config: {
    semi: false,
    arrowParens: "avoid",
    trailingComma: "none",
    singleQuote: true,
    endOfLine: "lf",
    bracketSpacing: true,
    printWidth: 80,
    useTabs: false,
    quoteProps: "as-needed",
    tabWidth: 2,
    importOrder: [
      "^(react/(.*)$)|^(react$)",
      "^(next/(.*)$)|^(next$)",
      "<THIRD_PARTY_MODULES>",
      "",
      "^@/types/(.*)$",
      "^@/components/(.*)$",
      "^@/lib/(.*)$",
      "^@/(.*)$",
      "^[./]",
    ],
    importOrderSeparation: true,
    importOrderSortSpecifiers: true,
  },
};
