import { cn } from "@/lib/utils/cn";
import { GeistSans } from "geist/font/sans";
import type { Metadata } from "next";
import { PropsWithChildren } from "react";
import "./globals.css";

export const metadata: Metadata = {
  title: "xyashino portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          GeistSans.className,
          "w-screen h-svh overflow-hidden relative bg-primary",
        )}
      >
        {children}
        <div id="portals" />
      </body>
    </html>
  );
}
