import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cn } from "@/lib/utils/cn";
import { PropsWithChildren } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "xyashino portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body
        className={cn(
          inter.className,
          "w-screen h-[100dvh]  overflow-hidden relative bg-primary",
        )}
      >
        {children}
        <div id="portals" />
      </body>
    </html>
  );
}
